---
title: "Group_Project"
author: "SZD"
date: "November 27, 2017"
output: html_document
---

```{r}

library(deSolve)
library(ggplot2)

predPreySim<-function(t,y,p){
  herbivore=y[1]
  carnivore=y[2]
  h_birthrate=p[1]
  c_attackrate=p[2]
  h_c_efficiency=p[3]
  c_death=p[4]
  dHerb_dt=(h_birthrate*herbivore)-(c_attackrate*carnivore*herbivore)
  dCarn_dt=(h_c_efficiency*c_attackrate*carnivore*herbivore)-(c_death*carnivore)
  return(list(c(dHerb_dt,dCarn_dt)))
}


y = c(25,5)
p = c(0.5,0.02,0.1,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2,aes(x=time)) + geom_line(aes(y=herbivore), colour="red") + geom_line(aes(y=predator),colour="blue")+theme_classic()+ylab("Counts")

```

```{r}

dprey_dt = c(0)
for(i in 2:length(modelSim[,2])){
  dprey_dt <- c(dprey_dt,modelSim[i,2]-modelSim[i-1,2])
}
t_dprey_dt <- t(dprey_dt)
plot(x=times, y=t_dprey_dt)

```

```{r}

dpredator_dt = c(0)
for(i in 2:length(modelSim[,3])){
  dpredator_dt <- c(dpredator_dt,modelSim[i,3]-modelSim[i-1,3])
}
t_dpredator_dt <- t(dpredator_dt)
plot(x=times, y=t_dpredator_dt)

```


```{r}
plot(x=t_dpredator_dt, y=t_dprey_dt)
```


```{r}
plot(x=modelSim2$predator, y=t_dprey_dt)
```

```{r}
plot(x=modelSim2$predator, y=modelSim2$herbivore)
```

```{r}

which(modelSim[,2]>round(max(modelSim[,2])))

```


```{r}

min(modelSim[,2])

  
```

```{r}

max(modelSim[,3])

```
```{r}

min(modelSim[,3])

```



```{r}
y = c(300,5)
p = c(0.5,0.02,0.1,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```


```{r}

max(modelSim[,2])

```


```{r}

max(modelSim[,3])

```

```{r}
y = c(5,5)
p = c(0.5,0.02,0.1,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

```{r}

which(modelSim[,2]>round(max(modelSim[,2]-1)))

```

```{r}

max(modelSim[,2])

```

```{r}

max(modelSim[,3])

```


Change p[1] from 0.5 to 0.08 (and time to 200)
```{r}
y = c(25,5)
p = c(0.08,0.02,0.1,0.2)
times=seq(from=1,to=200,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[1] from 0.5 to 0.8
```{r}
y = c(25,5)
p = c(0.8,0.02,0.1,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[2] from 0.02 to 0.1
```{r}
y = c(25,5)
p = c(0.5,0.1,0.1,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[2] from 0.02 to 0.001
```{r}
y = c(25,5)
p = c(0.5,0.001,0.1,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[3] from 0.1 to 0.5 
```{r}
y = c(25,5)
p = c(0.5,0.02,0.5,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[3] from 0.1 to 0.02
```{r}
y = c(25,5)
p = c(0.5,0.02,0.02,0.2)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[3] from 0.1 to 0.02
```{r}
summary(modelSim)
```

Change p[4] from 0.2 to 0.5
```{r}
y = c(25,5)
p = c(0.5,0.02,0.1,0.5)
times=seq(from=1,to=100,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick")+geom_line(aes(x=time,y=predator),color="royalblue")+theme_classic()+ylab("Counts")
```

Change p[4] from 0.2 to 0.02
```{r}
y = c(25,5)
p = c(0.5,0.02,0.1,0.02)
times=seq(from=1,to=1000,by=0.1)

modelSim=ode(y=y,times=times,func=predPreySim,parms=p)
colnames(modelSim)[2] <- "herbivore"
colnames(modelSim)[3] <- "predator"
modelSim2 <- as.data.frame(modelSim)
ggplot(data=modelSim2) + geom_line(aes(x=time,y=herbivore),color="firebrick",show.legend = TRUE)+geom_line(aes(x=time,y=predator),color="royalblue",show.legend = TRUE)+theme_classic()+ylab("Counts")

ggplot(data=modelSim2, aes=(herbivore
                            
                            
                            
                            
                            )) + geom_line(aes(herbivore,predator),color=c("firebrick","royalblue"))+theme_classic()+ylab("Counts")

```




